import { Stack, StackProps, CfnOutput } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { LearningPlanApi } from '../constructs/learning-plan-api';

export class LearningPlanStack extends Stack {
  public readonly apiEndpoint: string;

  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const api = new LearningPlanApi(this, 'LearningPlanApiConstruct', {
      apiName: 'Learning Plan API',
      apiDescription: 'Returns a learning plan generated by LLMs.',
      lambdaName: 'GetLearningPlanFunction',
    });

    // Store the API endpoint URL
    this.apiEndpoint = api.apiEndpoint;

    // Output the API endpoint URL
    new CfnOutput(this, 'ApiEndpoint', {
      value: this.apiEndpoint,
      description: 'The endpoint URL of the API Gateway',
      exportName: 'LearningPlanApiEndpoint',
    });
  }
}
