import { Stack, StackProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { LearningPlanApi } from '../constructs/learning-plan-api';


export class LeraningPlanStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    new LearningPlanApi(this, 'LearningPlanApiConstruct', {
      apiName: 'Learning Plan API',
      apiDescription: 'Returns a learning plan generated by LLMs.',
      lambdaName: 'GetLearningPlanFunction',
    });
  }
}
