#!/bin/bash

# Deploy the API stack first
echo "Deploying API stack..."
cdk deploy LearningPlanStack --require-approval never

# Get the API endpoint from the deployed stack
API_ENDPOINT=$(aws cloudformation describe-stacks --stack-name LearningPlanStack --query "Stacks[0].Outputs[?OutputKey=='LearningPlanApiConstructLearningPlanApiEndpointF24061D0'].OutputValue" --output text)

if [ -z "$API_ENDPOINT" ]; then
  echo "Error: Could not retrieve API endpoint from CloudFormation stack"
  exit 1
fi

# Create the .env file with the API endpoint
echo "# This file is automatically generated during deployment" > ../frontend/.env
echo "REACT_APP_API_URL=$API_ENDPOINT" >> ../frontend/.env

echo "Updated .env file with API endpoint: $API_ENDPOINT"

# Build the frontend
echo "Building the frontend..."
cd ../frontend && npm run build
cd ../CDK

# Deploy the frontend stack
echo "Deploying frontend stack..."
cdk deploy LearningPlanFrontendStack --require-approval never

# Deploy the Bedrock stack
echo "Deploying Bedrock stack..."
cdk deploy BedrockStack --require-approval never

echo "Deployment completed successfully!"
